### ISSUE TITLE
display_errors should be on be default

### ISSUE THREAD

**Issue by cweagans** [drud/docker.nginx-php-fpm-local#46]
## What happened (or feature request):

In a dev environment, we should see PHP errors by default. Basically, just flip all of this logic:

https://github.com/drud/docker.nginx-php-fpm-local/blob/4bc6883b625f5ae0327e6457d514ba8b86275dfb/files/start.sh#L24-L29

## Related source links or issues:

**Comment by rfay** [comment]
I agree with this one, just wonder if there might be any unexpected consequences.

**Comment by rfay** [comment]
Fixed in https://github.com/drud/docker.nginx-php-fpm-local/pull/60
